# Numpy

## 資料類型

NumPy內建了比Python更多的資料型別，如下:

- 布林: `bool_`、`bool8`
- 整數: `byte`、`short`、`intc`、`int_`、`longlong`、`intp`、`int8`、`int16`、`int32`、`int64`
- 無號整數: `ubyte`、`ushort`、`uintc`、`uint`、`ulonglong`、`uintp`、`uint8`、`uint16`、`uint32`、`uint64`
- 浮點數: `half`、`single`、`double`、`float_`、`longfloat`、`float16`、`float32`、`float64`、 `float96`、`float128`
- 複數浮點數: `csingle`、`complex_`、`clongfloat`、`complex64`、`complex128`、`complex192`、`complex256`
- 其它: `object_`、`bytes_`、`unicode_`、`void`

## 陣列

- 陣列 (array) 可以用來存放多個資料。
- 陣列所存放的資料叫做元素 (element)，每個元素有各自的值 (value)。
- 陣列是透過索引 (index) 來區分它所存放的元素，多數程式語言是以索引 `0` 代表陣列的第 `1` 個元素，索引 `1` 代表陣列的第 `2` 個元素，…， 索引 `n - 1` 代表陣列的第 `n` 個元素。

![Array](ppt-array.png)

In [1]:
import numpy as np
import nptyping as npt

## 一維陣列

- NumPy 提供的陣列型別叫做 `ndarray` (n-dimension array, n 維陣列)，`n` 維、同質且固定大小的陣列物件。
  - $n$ 維代表可以是一維、二維或是更多維
  - 同質代表每個元素必須是相同型別

## 建立方式

- `np.array`: 從串列 (list) 或序對 (tuple) 建立一維陣列
- `np.zeros`: 建立都是 0 的陣列
- `np.ones`: 建立都是 1 的陣列
- `np.empty`: 建立未初始化的陣列
- `np.arange`: 建立數列
- `np.linsapce`: 建立平均分佈的數值

In [2]:
print(f"{np.array([1,2,3,4], dtype=np.int8) = }")
print(f"{np.zeros(4, dtype=np.int8) = }")
print(f"{np.ones(4, dtype=np.int8) = }")
print(f"{np.empty(4, dtype=np.int8) = }")


np.array([1,2,3,4], dtype=np.int8) = array([1, 2, 3, 4], dtype=int8)
np.zeros(4, dtype=np.int8) = array([0, 0, 0, 0], dtype=int8)
np.ones(4, dtype=np.int8) = array([1, 1, 1, 1], dtype=int8)
np.empty(4, dtype=np.int8) = array([1, 1, 1, 1], dtype=int8)


In [3]:
print(f"{np.arange(10, dtype=np.int8) = }")
print(f"{np.arange(start=3, stop=30, step=3, dtype=np.int8) = }")

np.arange(10, dtype=np.int8) = array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)
np.arange(start=3, stop=30, step=3, dtype=np.int8) = array([ 3,  6,  9, 12, 15, 18, 21, 24, 27], dtype=int8)


In [4]:
print(f"{np.linspace(0, 2, 9) = }")
print(f"{np.linspace(1, 3, 5) = }")

np.linspace(0, 2, 9) = array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])
np.linspace(1, 3, 5) = array([1. , 1.5, 2. , 2.5, 3. ])


## 屬性

- `ndarray.ndim` : 陣列的維度，NumPy 將維度 (dimension) 稱為 axis (軸)
- `ndarray.shape` : 陣列的形狀，代表每個維度的元素個數
- `ndarray.size` : 陣列的元素個數
- `ndarray.dtype` : 陣列的元素型別
- `ndarray.itemsize` : 陣列的大小 (以 byte 位元組為單位)

## 運算子

In [5]:
A = np.array([10, 20, 30, 40, 50])
B = np.array([1, 2, 3, 4, 5])

print(f"{A * 2 = }") # 對 array 內的每個元素做 x2 運算
print(f"{A ** 2 = }") # 對 array 內的每個元素做 2次方 運算
print(f"{A < 35 = }") # 對 array 內的每個元素做 條件式 判斷
print(f"{A + B = }") # 兩個 array 相加


A * 2 = array([ 20,  40,  60,  80, 100])
A ** 2 = array([ 100,  400,  900, 1600, 2500])
A < 35 = array([ True,  True,  True, False, False])
A + B = array([11, 22, 33, 44, 55])


## 索引

### 單元素索引

Single element indexing works exactly like that for other standard Python sequences. It is 0-based, and accepts negative indices for indexing from the end of the array.

In [6]:
x = np.arange(10)
print(x[2]) # 2
print(x[-2]) # 8

x[2] = 4
print(x[2])

x[2] = 2 # restore

2
8
4


In [7]:
x.shape = (2, 5)  # now x is 2-dimensional
print(x[1, 3]) # 8
print(x[1, -1]) # 9

8
9


Note that if one indexes a multidimensional array with fewer indices than dimensions, one gets a subdimensional array. For example:

In [8]:
print(x[0])

[0 1 2 3 4]


In [9]:
A = np.array([[1, 1], [0, 1]])

print(f"{A[0, 0] = }")
print(f"{A[[0, 0], [1,1]] = }")

A[0, 0] = 1
A[[0, 0], [1,1]] = array([1, 1])


## Slicing

The basic slice syntax is `i:j:k` where `i` is the starting index, `j` is the stopping index, and `k` is the step ($k \not= 0$).

In [10]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x[1:7:2])    # array([1, 3, 5])
print(x[-2:10])    # array([8, 9   ])
print(x[-3:3:-1])  # array([7, 6, 5, 4])

[1 3 5]
[8 9]
[7 6 5 4]


## Ellipsis ($\cdots$)

<https://note.nkmk.me/en/python-numpy-ellipsis/>

In NumPy, you can use Ellipsis (...) to omit intermediate dimensions when specifying elements or ranges with `[]`.


In [11]:
import numpy as np

a = np.arange(120).reshape(2, 3, 4, 5)

print(a.shape)
# (2, 3, 4, 5)

print(a[:, :, :, 0])

# can be simplified to:

print(a[..., 0])

(2, 3, 4, 5)
[[[  0   5  10  15]
  [ 20  25  30  35]
  [ 40  45  50  55]]

 [[ 60  65  70  75]
  [ 80  85  90  95]
  [100 105 110 115]]]
[[[  0   5  10  15]
  [ 20  25  30  35]
  [ 40  45  50  55]]

 [[ 60  65  70  75]
  [ 80  85  90  95]
  [100 105 110 115]]]


### Integer array indexing (連續選擇)

Integer array indexing allows selection of arbitrary items in the array based on their N-dimensional index. Each integer array represents a number of indices into that dimension.

Negative values are permitted in the index arrays and work as they do with single indices or slices:

In [12]:
x = np.arange(10, 1, -1)

print(f"{x = }")
print(f"{x[[3, 3, 1, 8]] = }")
print(f"{x[[3, 3, -3, 8]] = }")

x = array([10,  9,  8,  7,  6,  5,  4,  3,  2])
x[[3, 3, 1, 8]] = array([7, 7, 9, 2])
x[[3, 3, -3, 8]] = array([7, 7, 4, 2])


In [13]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print(f"{x[np.array([1, -1])] = }")

try:
    print(f"{x[np.array([3, 4])] = }")
except Exception as e:
    print("Error:", e)

print(f"{x[np.array([1, -1]), 1] = }")
print(f"{x[np.array([1, -1]), [0, 1]] = }")


x[np.array([1, -1])] = array([[3, 4],
       [5, 6]])
Error: index 3 is out of bounds for axis 0 with size 3
x[np.array([1, -1]), 1] = array([4, 6])
x[np.array([1, -1]), [0, 1]] = array([3, 6])


## 一維陣列運算

- `insert()` 函式在陣列中插入元素
- `delete()` 函式在陣列中刪除元素
- `concatenate()` 函式結合兩個陣列或加入元素
- `dots()` 函式計算向量內積
- `cross()` 函式計算向量外積

In [14]:
from nptyping import Int, NDArray, Shape


A: NDArray[Shape["5"], Int] = np.array([10, 20, 30, 40, 50], dtype=np.int8)
print(f"{np.insert(A, 1, 100) = }")  # (arr, position, value)
print(f"{np.delete(A, 3) = }")  # (arr, position)
print(f"{np.concatenate((A, np.ones(4, dtype=np.int8)))}")

np.insert(A, 1, 100) = array([ 10, 100,  20,  30,  40,  50], dtype=int8)
np.delete(A, 3) = array([10, 20, 30, 50], dtype=int8)
[10 20 30 40 50  1  1  1  1]


下列範例建立兩個一維陣列，並嘗試將兩個陣列進行四則運算。

In [15]:
arr1: npt.NDArray[npt.Shape['5'], npt.Int] = np.array([114, 514, 191, 8, 10])
arr2: npt.NDArray[npt.Shape['5'], npt.Int] = np.array([1919, 810, 191, 8, 10])

print(f"{arr1 + arr2 = }")
print(f"{arr1 - arr2 = }")
print(f"{arr1 * arr2 = }")
print(f"{arr1 / arr2 = }")

arr1 + arr2 = array([2033, 1324,  382,   16,   20])
arr1 - arr2 = array([-1805,  -296,     0,     0,     0])
arr1 * arr2 = array([218766, 416340,  36481,     64,    100])
arr1 / arr2 = array([0.05940594, 0.6345679 , 1.        , 1.        , 1.        ])


下列範例建立兩個一維陣列如 arr3, arr4 並計算其內積和外積。

In [16]:
arr3: npt.NDArray[npt.Shape['3'], npt.Int] = np.array([2,3,54])
arr4: npt.NDArray[npt.Shape['3'], npt.Int] = np.array([123,123,522])

print(f"{np.dot(arr3, arr4) = }")
print(f"{np.cross(arr3, arr4) = }")

np.dot(arr3, arr4) = 28803
np.cross(arr3, arr4) = array([-5076,  5598,  -123])


## 二維陣列

In [17]:
grades: npt.NDArray[npt.Shape["5,3"], npt.Int] = np.array([
    [95, 100, 100],
    [86, 90, 75],
    [98, 98, 96],
    [78, 90, 80],
    [70, 68, 72]
])

print(f"{grades = }")
print(f"{grades[1,2] = }")

grades = array([[ 95, 100, 100],
       [ 86,  90,  75],
       [ 98,  98,  96],
       [ 78,  90,  80],
       [ 70,  68,  72]])
grades[1,2] = 75


- `reshape()` 函式改變陣列的維度
- `ravel()` 函式將多維陣列轉換成一維陣列

In [18]:
print(f"{np.arange(15).reshape(3, 5) = }")

np.arange(15).reshape(3, 5) = array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])


In [19]:
print(f"{np.arange(15).reshape(3, 5).ravel() = }")

np.arange(15).reshape(3, 5).ravel() = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


運算子也和一維類似，都作用在每個元素上。

- `transpose()`: 轉置

In [20]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 2], [1, 1]])
print(A * 2) # 陣列元素 x2
print(A > 2) # 陣列元素做條件式比較
print(A + B) # 兩個陣列相加

[[2 4]
 [6 8]]
[[False False]
 [ True  True]]
[[3 4]
 [4 5]]


In [21]:
A = np.array([[1, 2], [3, 4]])
A[0, 0] = 7
print(A)

[[7 2]
 [3 4]]


下列範例建立一個二維陣列 arr1，並將 arr1 與此陣列的轉置矩陣相加。

In [22]:
arr1 = np.arange(start=2, stop=33, step=2).reshape((4, 4))

transpose = arr1.transpose()
print(f"{arr1 + transpose = }")

arr1 + transpose = array([[ 4, 14, 24, 34],
       [14, 24, 34, 44],
       [24, 34, 44, 54],
       [34, 44, 54, 64]])


# 通用函式

NumPy提供了諸如sin()、cos()、exp()、square()、add() 等常見的數學函式，並稱為通用函式 (ufunc，universal functions)，因為這些函式會逐一作用在陣列的每個元素，然後傳回一個陣列

In [23]:
import numpy as np

A = np.array([1, 2, 3])
B = np.square(A)
print(B)

[1 4 9]


## 數學函式

- **三角函式**: `cos(x)`、`sin(x)`、`tan(x)`、`acos(x)`、`asin(x)`、`atan(x)`
- **四捨五入**: `round_(x, decimals=0)`、`rint(x)`、`floor(x)`、`ceil(x)`、`trunc(x)`
- **和/積/差**: `prod(a, axis=None)`、`cumprod(a, axis=None)`、`sum(a, axis=None)`、`cumsum(a, axis=None)`、`diff(a, n=1, axis=-1)`、`cross(a, b)`
- **指數與對數**: `exp(x)`、`exp2(x)`、`log(x)`、`log2(x)`、`log10(x)`
- **算術運算**: `add(x1, x2)`、`subtract(x1, x2)`、`multiply(x1, x2)`、`divide(x1, x2)`、`power(x1, x2)`、`mod(x1, x2)`、`remainder(x1, x2)`、`fmod(x1, x2)`、`divmod(x1, x2)`、`negative(x)`
- **其它**: `sign(x)`、`absolute(x)`、`sqrt(x)`、`cbrt(x)`、`square(x)`、`maximum(x1, x2)`、`minimum(x1, x2)`、`gcd(x1, x2)`
- 其它實用函式: `isinf(x)`、`isfinite(x)`、`isnan(x)`、`max(x)`、`min(x)`、`sort(x)`


以下的範例使用這些函式計算：

- sin0°、sin30°、sin45°
- cos30°、cos45°、cos60°
- tan30°、tan45°、tan60°

的值。

注意三角函數函式要求傳入的角度單位是弧度 (radian)，而非角度 (degree)。

角度轉換成弧度的公式：$1°= \frac{\pi}{180} \text{rad}$

In [24]:
import numpy as np

# 
print(f"{np.sin(np.array([0, 30, 45]) * np.pi / 180.) = }")
print(f"{np.cos(np.array([30, 45, 60]) * np.pi / 180.) = }")
print(f"{np.tan(np.array([30, 45, 60]) * np.pi / 180.) = }")

np.sin(np.array([0, 30, 45]) * np.pi / 180.) = array([0.        , 0.5       , 0.70710678])
np.cos(np.array([30, 45, 60]) * np.pi / 180.) = array([0.8660254 , 0.70710678, 0.5       ])
np.tan(np.array([30, 45, 60]) * np.pi / 180.) = array([0.57735027, 1.        , 1.73205081])


## 取亂數

- `rand(d0, d1, ..., dn)`
- `randn(d0, d1, ..., dn)`
- `randint(low[, high, size, dtype])`
- `random_integers(low[, high, size])`

In [25]:
print(f"{np.random.random(3) = }")

np.random.random(3) = array([0.88346672, 0.62336326, 0.09437927])


In [26]:
print(f"{np.random.randint(1, 24, 3) = }")

np.random.randint(1, 24, 3) = array([ 1, 10, 18])


下列範例建立一個陣列，長度為 20，元素值為 1-100 的亂數值。

In [27]:
print(f"{np.random.randint(1, 100, 20) = }")

np.random.randint(1, 100, 20) = array([62, 29, 94, 80, 62, 34, 17, 63, 61,  8, 63, 82, 51,  6, 33, 63,  7,
       39, 59, 94])
